### ISSUE TITLE
No tasks.MultiModelFit PycoTools in version pycotools3-2.1.7 or pycotools3-2.1.10

### ISSUE THREAD

**Issue by Niels86** [CiaranWelsh/PyCoTools#11]
Dear Ciaran,

I tried to run example 1.3.3 from the supplementary material, I got the AttributeError: module 'pycotools3.tasks' has no attribute 'MultiModelFit'
All examples up to that point as well as running time series simulations with some models of my own worked fine. Any idea what might be the problem? Was this function removed or not available in pycotools3-2.1.7 or pycotools3-2.1.10 or maybe renamed? 
I also noted tasks.MultiModelFit functions is not described or mentioned in the documentation at htps://pycotools3.readthedocs.io

Regards, 

Niels Zondervan

**Comment by Niels86** [comment]
A, I found the solution in the documentation >_<, should have known. So the function has been removed and now instead you feed a list of models to the parameter estimation as described on:
https://pycotools3.readthedocs.io/en/latest/Examples/parameter_estimation_multiple_models.html

Thx for creating such a great Toolbox, could have saved me 1-2 years in my PhD!

**Comment by CiaranWelsh** [comment]
Hi Niels, 

No problem, I'm fairly certain I've made similar mistakes in the past... Happy to help if you need it,  

Best, 

Ciaran
